# Generated by Django 4.1.2 on 2022-10-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Задача", "verbose_name_plural": "Задачи"},
        ),
    ]
